/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package example.day.interest;

public class InterestCalculator {

    private final double creditInterestRate = 0.05;
    private final double bonusInterestRate = 0.01;
    private final double debetInterestRate = 0.10;

    public double dayInterest(double amount) {
        double interest = 0.0;
        if (amount >= 250000.0) {
            interest = amount * creditInterestRate / 365;
            interest += amount * bonusInterestRate / 365;
        } else if (amount >= 0.0) {
            interest = amount * creditInterestRate / 365;
        } else {
            interest = amount * debetInterestRate / 365;
        }
        return interest;
    }

}
