/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package examples.presentation;

import org.assertj.core.data.Offset;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import static org.assertj.core.api.Java6Assertions.assertThat;
import static org.assertj.core.data.Offset.strictOffset;

class ValidationUtilsTest {


    private Validator validator = new Validator();

    @Test
    void emptyArrayIsValid() {
        assertThat(validator.isValid(new String[]{})).isTrue();
    }

    @Test
    void arrayContainingNonEmptyStringIsValid() {
        assertThat(validator.isValid(new String[]{"non-empty"})).isTrue();
    }

    @Test
    void arrayContainingEmptyStringIsInvalid() {
        assertThat(validator.isValid(new String[]{""})).isFalse();
    }

    @Test
    void arrayContainingNullStringIsInvalid() {
        assertThat(validator.isValid(new String[]{null})).isFalse();
    }

    @Test
    void arrayContainingNonEmptyStringsIsValid() {
        assertThat(validator.isValid(new String[]{"non-empty","yet-another"})).isTrue();
    }

    @Test
    void arrayContainingSingleEmptyStringIsInvalid() {
        assertThat(validator.isValid(new String[]{"non-empty",""})).isFalse();
    }

    @Test
    void arrayContainingSingleNullStringIsInvalid() {
        assertThat(validator.isValid(new String[]{"non-empty",null})).isFalse();
    }
}
