/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package examples.presentation;

public class Validator {

    public Validator() {}

    boolean isValid(String[] items) {
        boolean flag = true;

        for (int i = 0; i < items.length; i++) {
            String item = items[i];
            if (( item != null && item.length() != 0))
                continue;

            flag = false;
            break;
        }

        return flag;
    }
}
